export const OPEN_MY_HIVES = "OPEN_MY_HIVES";
export const CLOSE_MY_HIVES = "CLOSE_MY_HIVES";

export const OPEN_SAVED_STATEMENTS = "GO_TO_SAVED_STATEMENTS";
export const CLOSE_SAVED_STATEMENTS = "CLOSE_SAVED_STATEMENTS"

export const OPEN_HIVE_YARD = "OPEN_HIVE_YARD";
export const CLOSE_HIVE_YARD = "CLOSE_HIVE_YARD";

export const OPEN_CREATE_NEW_HIVE = "OPEN_CREATE_NEW_HIVE";
export const CLOSE_CREATE_NEW_HIVE = "CLOSE_CREATE_NEW_HIVE";

export const INIT_CREATING_NEW_HIVE = "BEGIN_CREATING_NEW_HIVE";
export const NEW_HIVE_CREATED = "NEW_HIVE_CREATED";

export const SEARCHED_STATEMENTS_FOUND = "SEARCHED_STATEMENTS_FOUND";
export const SEARCHED_HIVES_FOUND = "SEARCHED_HIVES_FOUND";

export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOADED = "USER_LOADED";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const HIVE_LOADED = "HIVE_INFO_LOADED";
export const USER_SAVED_HIVES_LOADED = "USER_SAVED_HIVES_LOADED";
export const SUBGRAPH_LOADED = "HIVE_DATA_LOADED";

export const SELECT_DEFAULT_HIVE = "SELECT_DEFAULT_HIVE"

export const SELECT_STATEMENT = "SELECT_STATEMENT"
export const CREATE_STATEMENT = "CREATE_STATEMENT"
export const CONNECT_STATEMENT_TO_STATEMENT = "CONNECT_STATEMENT_TO_STATEMENT"
export const RESPOND_TO_STATEMENT = "RESPOND_TO_STATEMENT"
export const RESPOND_TO_SYNAPSE = "RESPOND_TO_SYNAPSE"

export const UPDATE_RESPONSE_VIEW = "UPDATE_RESPONSE_VIEW"
export const UPDATE_LAYOUT = "UPDATE_LAYOUT"