export const OPEN_LOGIN = "OPEN_LOGIN";
export const CLOSE_LOGIN = "CLOSE_LOGIN";
export const OPEN_MY_HIVES = "OPEN_MY_HIVES";
export const CLOSE_MY_HIVES = "CLOSE_MY_HIVES";
export const OPEN_SAVED_STATEMENTS = "GO_TO_SAVED_STATEMENTS";
export const CLOSE_SAVED_STATEMENTS = "CLOSE_SAVED_STATEMENTS"

export const LOGIN = "LOGIN";
export const LOAD_USER = "LOAD_USER";
export const LOGOUT = "LOGOUT"

export const LOAD_HIVE_INFO = "LOAD_HIVE_INFO";
export const LOAD_HIVE_DATA = "LOAD_HIVE_DATA";

export const SELECT_DEFAULT_HIVE = "SELECT_DEFAULT_HIVE"

export const SELECT_STATEMENT = "SELECT_STATEMENT"
export const CREATE_STATEMENT = "CREATE_STATEMENT"
export const CONNECT_STATEMENT_TO_STATEMENT = "CONNECT_STATEMENT_TO_STATEMENT"
export const RESPOND_TO_STATEMENT = "RESPOND_TO_STATEMENT"
export const RESPOND_TO_SYNAPSE = "RESPOND_TO_SYNAPSE"

export const UPDATE_RESPONSE_VIEW = "UPDATE_RESPONSE_VIEW"
export const UPDATE_LAYOUT = "UPDATE_LAYOUT"